/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PublicacoesRouteImport } from './routes/publicacoes'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicacoesSlugRouteImport } from './routes/publicacoes.$slug'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as MembrosSlugRouteImport } from './routes/membros.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminPublicacoesRouteImport } from './routes/admin/publicacoes'
import { Route as AdminProjetosRouteImport } from './routes/admin/projetos'
import { Route as AdminNoticiasRouteImport } from './routes/admin/noticias'
import { Route as AdminMembrosRouteImport } from './routes/admin/membros'
import { Route as AdminUsuariosIdRouteImport } from './routes/admin/usuarios.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesRoute = PublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesSlugRoute = PublicacoesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicacoesRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const MembrosSlugRoute = MembrosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MembrosRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPublicacoesRoute = AdminPublicacoesRouteImport.update({
  id: '/admin/publicacoes',
  path: '/admin/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/admin/projetos',
  path: '/admin/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticiasRoute = AdminNoticiasRouteImport.update({
  id: '/admin/noticias',
  path: '/admin/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembrosRoute = AdminMembrosRouteImport.update({
  id: '/admin/membros',
  path: '/admin/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosIdRoute = AdminUsuariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsuariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/pesquisa': typeof PesquisaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/publicacoes': typeof PublicacoesRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/publicacoes': typeof AdminPublicacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/membros/$slug': typeof MembrosSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/publicacoes/$slug': typeof PublicacoesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/pesquisa': typeof PesquisaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/publicacoes': typeof PublicacoesRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/publicacoes': typeof AdminPublicacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/membros/$slug': typeof MembrosSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/publicacoes/$slug': typeof PublicacoesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/pesquisa': typeof PesquisaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/publicacoes': typeof PublicacoesRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/publicacoes': typeof AdminPublicacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/membros/$slug': typeof MembrosSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/publicacoes/$slug': typeof PublicacoesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/membros'
    | '/noticias'
    | '/pesquisa'
    | '/projetos'
    | '/publicacoes'
    | '/sobre'
    | '/admin/membros'
    | '/admin/noticias'
    | '/admin/projetos'
    | '/admin/publicacoes'
    | '/admin/usuarios'
    | '/membros/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/publicacoes/$slug'
    | '/admin/'
    | '/admin/usuarios/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/membros'
    | '/noticias'
    | '/pesquisa'
    | '/projetos'
    | '/publicacoes'
    | '/sobre'
    | '/admin/membros'
    | '/admin/noticias'
    | '/admin/projetos'
    | '/admin/publicacoes'
    | '/admin/usuarios'
    | '/membros/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/publicacoes/$slug'
    | '/admin'
    | '/admin/usuarios/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/membros'
    | '/noticias'
    | '/pesquisa'
    | '/projetos'
    | '/publicacoes'
    | '/sobre'
    | '/admin/membros'
    | '/admin/noticias'
    | '/admin/projetos'
    | '/admin/publicacoes'
    | '/admin/usuarios'
    | '/membros/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/publicacoes/$slug'
    | '/admin/'
    | '/admin/usuarios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MembrosRoute: typeof MembrosRouteWithChildren
  NoticiasRoute: typeof NoticiasRouteWithChildren
  PesquisaRoute: typeof PesquisaRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  PublicacoesRoute: typeof PublicacoesRouteWithChildren
  SobreRoute: typeof SobreRoute
  AdminMembrosRoute: typeof AdminMembrosRoute
  AdminNoticiasRoute: typeof AdminNoticiasRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminPublicacoesRoute: typeof AdminPublicacoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes': {
      id: '/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes/$slug': {
      id: '/publicacoes/$slug'
      path: '/$slug'
      fullPath: '/publicacoes/$slug'
      preLoaderRoute: typeof PublicacoesSlugRouteImport
      parentRoute: typeof PublicacoesRoute
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/membros/$slug': {
      id: '/membros/$slug'
      path: '/$slug'
      fullPath: '/membros/$slug'
      preLoaderRoute: typeof MembrosSlugRouteImport
      parentRoute: typeof MembrosRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/publicacoes': {
      id: '/admin/publicacoes'
      path: '/admin/publicacoes'
      fullPath: '/admin/publicacoes'
      preLoaderRoute: typeof AdminPublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/admin/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/noticias': {
      id: '/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminNoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/membros': {
      id: '/admin/membros'
      path: '/admin/membros'
      fullPath: '/admin/membros'
      preLoaderRoute: typeof AdminMembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios/$id': {
      id: '/admin/usuarios/$id'
      path: '/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AdminUsuariosIdRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
  }
}

interface MembrosRouteChildren {
  MembrosSlugRoute: typeof MembrosSlugRoute
}

const MembrosRouteChildren: MembrosRouteChildren = {
  MembrosSlugRoute: MembrosSlugRoute,
}

const MembrosRouteWithChildren =
  MembrosRoute._addFileChildren(MembrosRouteChildren)

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

interface PublicacoesRouteChildren {
  PublicacoesSlugRoute: typeof PublicacoesSlugRoute
}

const PublicacoesRouteChildren: PublicacoesRouteChildren = {
  PublicacoesSlugRoute: PublicacoesSlugRoute,
}

const PublicacoesRouteWithChildren = PublicacoesRoute._addFileChildren(
  PublicacoesRouteChildren,
)

interface AdminUsuariosRouteChildren {
  AdminUsuariosIdRoute: typeof AdminUsuariosIdRoute
}

const AdminUsuariosRouteChildren: AdminUsuariosRouteChildren = {
  AdminUsuariosIdRoute: AdminUsuariosIdRoute,
}

const AdminUsuariosRouteWithChildren = AdminUsuariosRoute._addFileChildren(
  AdminUsuariosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MembrosRoute: MembrosRouteWithChildren,
  NoticiasRoute: NoticiasRouteWithChildren,
  PesquisaRoute: PesquisaRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  PublicacoesRoute: PublicacoesRouteWithChildren,
  SobreRoute: SobreRoute,
  AdminMembrosRoute: AdminMembrosRoute,
  AdminNoticiasRoute: AdminNoticiasRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminPublicacoesRoute: AdminPublicacoesRoute,
  AdminUsuariosRoute: AdminUsuariosRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
